// <auto-generated>
//     GENERATED FILE - DO NOT EDIT BY HAND.
//
//     Source:    src/data/demoPassSchedule.ts
//     Generator: scripts/exportTagCatalog.ts
//     Regenerate with:  npx tsx scripts/exportTagCatalog.ts
// </auto-generated>

using Crm04.Domain.Types;

namespace Crm04.Domain.Coils;

/// <summary>
/// The demo coil and its 5-pass schedule, "ABP / plant pass schedule system (DEMO — representative schedule, not a production coil)".
///
/// A REPRESENTATIVE schedule, not a production coil - the panel says so. Reductions and predicted
/// forces are derived in the TypeScript from the raw thicknesses, so they are generated here
/// rather than copied.
/// </summary>
internal static class PassScheduleData
{
    internal static readonly CoilData Coil = new(
        Id: "C4-250901-0142",
        Grade: "IS 513 CR2 / low-carbon drawing quality",
        Width: 450d,
        EntryThickness: 2.8d,
        FinalThickness: 0.9d,
        Mass: 0d,
        InnerDiameter: 508d,
        OuterDiameter: 1800d);

    internal const string Source = "ABP / plant pass schedule system (DEMO — representative schedule, not a production coil)";

    internal static readonly PassScheduleEntry[] Passes =
    [
        new PassScheduleEntry(1, RollingDirection.Forward, 2.8d, 2.15d, 23.21428571428571d, 180d, 45d, 62d, 248.7740239809377d),
        new PassScheduleEntry(2, RollingDirection.Reverse, 2.15d, 1.68d, 21.86046511627907d, 210d, 55d, 75d, 257.71903018291425d),
        new PassScheduleEntry(3, RollingDirection.Forward, 1.68d, 1.33d, 20.833333333333325d, 260d, 68d, 92d, 249.19666966319954d),
        new PassScheduleEntry(4, RollingDirection.Reverse, 1.33d, 1.08d, 18.796992481203006d, 330d, 82d, 110d, 229.51831501272304d),
        new PassScheduleEntry(5, RollingDirection.Forward, 1.08d, 0.9d, 16.66666666666667d, 420d, 100d, 128d, 208.35040866308975d),
    ];
}
