using System.Diagnostics.CodeAnalysis;

namespace Crm04.Domain.Telemetry;

/// <param name="TagName">
/// The tag that owns this signal. This is the load-bearing field: a chart series inherits its
/// provenance badge from here, so an ESTIMATED signal is drawn labelled ESTIMATED rather than as
/// an anonymous line that looks exactly like a measurement.
/// </param>
/// <param name="IsReference">A setpoint series - drawn dashed, and excluded from the KPI tier.</param>
/// <param name="Ordinal">Stable position, used the same way the tag ordinal is.</param>
public sealed record SignalDescriptor(
    string Key,
    string Label,
    string Unit,
    string Color,
    int Decimals,
    string Group,
    string TagName,
    bool IsReference,
    int Ordinal);

/// <param name="Key">"1m", "5m", "15m", "30m", "1h".</param>
/// <param name="Ms">Window length in milliseconds.</param>
public sealed record TrendWindow(string Key, long Ms)
{
    /// <summary>
    /// Points retained per window. 240 is about one point per 4 px on a full-width chart, which
    /// is the resolution beyond which more data draws no more picture.
    /// </summary>
    public const int Capacity = 240;

    /// <summary>
    /// How often to emit one averaged point. Downsampling happens ON WRITE, not on render: the
    /// 1-hour window stores a point every 15 s rather than 36,000 raw points that a chart would
    /// then have to decimate on every repaint.
    /// </summary>
    public double IntervalMs => (double)Ms / Capacity;
}

/// <summary>
/// The trend signals and windows, ported from <c>src/store/telemetryStore.ts</c> and
/// <c>src/types/telemetry.ts</c>.
///
/// The records are generated by <c>scripts/exportTagCatalog.ts</c>; this file holds the lookups
/// so regenerating never clobbers logic.
/// </summary>
public static class SignalCatalog
{
    private static readonly Dictionary<string, SignalDescriptor> ByKey =
        SignalCatalogData.Signals.ToDictionary(s => s.Key, StringComparer.Ordinal);

    private static readonly Dictionary<string, TrendWindow> WindowByKey =
        SignalCatalogData.Windows.ToDictionary(w => w.Key, StringComparer.Ordinal);

    public static IReadOnlyList<SignalDescriptor> All { get; } = SignalCatalogData.Signals;

    public static IReadOnlyList<TrendWindow> Windows { get; } = SignalCatalogData.Windows;

    public static int Count => SignalCatalogData.Signals.Length;

    /// <summary>Groups in declaration order, so a signal sits under the same heading everywhere.</summary>
    public static IReadOnlyList<string> Groups { get; } =
        SignalCatalogData.Signals.Select(s => s.Group).Distinct(StringComparer.Ordinal).ToList();

    public static SignalDescriptor? TryGet(string key) => ByKey.GetValueOrDefault(key);

    public static bool TryGet(string key, [NotNullWhen(true)] out SignalDescriptor? signal) =>
        ByKey.TryGetValue(key, out signal);

    public static TrendWindow? TryGetWindow(string key) => WindowByKey.GetValueOrDefault(key);

    /// <summary>The default window when a client asks for something unrecognised.</summary>
    public static TrendWindow DefaultWindow => WindowByKey["5m"];
}

/// <param name="T">Epoch milliseconds.</param>
/// <param name="V">The averaged value over this point's interval.</param>
public readonly record struct TrendPoint(long T, double V);
